import { getToken, clearToken, currentIdentity } from '../auth/authClient';

// At runtime in the static build, the bundled VITE_API_BASE is empty.
// Default to the gateway on the same host. Override by setting
// VITE_API_BASE at build time if you want a different gateway URL.
const API_BASE =
  (import.meta.env.VITE_API_BASE as string | undefined) ||
  `${window.location.protocol}//${window.location.hostname}:8080`;

/**
 * Cross-project Reconciliation Pattern. One row per
 * (vendor_family, kind, path) — surfaced on Stage C decision cards
 * as "Recommended (based on N prior migrations)" hints.
 */
export type ReconPattern = {
  vendor_family: string;
  kind: string;
  path: string;
  recommendation: string;
  summary: string;
  occurrence_count: number;
  confidence: 'low' | 'medium' | 'high';
  first_seen_at?: string;
  last_seen_at?: string;
  // Provenance — populated by V3__pattern_provenance migration.
  // The pattern banner uses these to show the customer where each
  // recommendation actually came from (which Nous engagement, which
  // engineer, when).
  first_seen_engagement?: string;
  confirmed_by?: string;
  /** Raw JSON text; engagement entries are { engagement, completed, engineer, outcome }. */
  engagement_history?: string;
};

export type ReconPatternsResponse = {
  projectId: string;
  count: number;
  patterns: ReconPattern[];
};

/**
 * Stage F Build & Test gate result. The gate runs `mvn compile` (SOAP)
 * or `mvn test` (UPLIFT) in a sandboxed JVM and reports back what
 * actually happened: did the code build, did the tests pass, which
 * ones failed. This is the enterprise-readiness checkpoint between
 * "Atlas generated some code" and "you can ship this".
 */
export type BuildTestRun = {
  id: string;
  projectId: string;
  status: 'running' | 'passed' | 'compile_failed' | 'tests_failed' | 'sandbox_limited' | 'error';
  track: string;
  filesCompiled: number;
  compileErrors: number;
  testsTotal: number;
  testsPassed: number;
  testsFailed: number;
  testsSkipped: number;
  durationMs?: number;
  logText?: string;
  failures?: string[];
  startedAt?: string;
  finishedAt?: string;
};
export type BuildTestResult = BuildTestRun & { runId: string };

/**
 * Atlas-at-work numbers shown on the workspace dashboard. Aggregated
 * by prj-service from prj.project + recon.pattern. All counts scoped
 * to vendor families this workspace's projects touch.
 */
export type WorkspaceInsights = {
  workspaceId: string;
  projectCount: number;
  patternCount: number;
  vendorCount: number;
  decisionsRemembered: number;
  hoursSavedEstimate: number;
};

/**
 * Migration Forecast — the pre-Stage-A effort estimate. Generated by
 * prj-service's ForecastService: structural AST peek (arch-service) +
 * grounded LLM call. One per project; re-running overwrites.
 */
export type MigrationForecast = {
  projectId: string;
  generatedAt: string;
  estimatedWeeks: number;
  confidence: 'LOW' | 'MEDIUM' | 'HIGH';
  topRisks: Array<{
    title: string;
    detail: string;
    severity: 'LOW' | 'MEDIUM' | 'HIGH';
  }>;
  rationale: string;
  structuralFacts: {
    javaFileCount?: number;
    operationCount?: number;
    typeMappingCount?: number;
    adapterCount?: number;
    complexityFlags?: string[];
    operations?: Array<{
      namespace?: string;
      name?: string;
      inputType?: string;
      outputType?: string;
      soapStyle?: string;
      flags?: string;
    }>;
  };
  model?: string;
  costUsd?: number;
  latencyMs?: number;
};

export type Project = {
  id: string;
  name: string;
  description?: string;
  mode: 'SOAP' | 'UPLIFT';
  sourceFramework?: string;
  targetFramework?: string;
  vendorPartner?: string;
  owner?: string;
  riskTier: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  currentStage: 'A' | 'B' | 'C' | 'D' | 'E' | 'F';
  sourcePath?: string;
  updatedAt?: string;
};

export type Operation = {
  id: string;
  namespace: string;
  name: string;
  inputType: string;
  outputType: string;
  sourceClass: string;
  sourceLines: number[];
  flags: string[];
  faultTypes: string[];
  confidence: 'low' | 'medium' | 'high';
  decisionState: 'pending' | 'accepted' | 'flagged' | 'modified' | 'rejected';
  typeMappings: Array<{
    javaType: string;
    qnameNamespace: string;
    qnameLocal: string;
    adapterFqn?: string;
    notes?: string;
  }>;
  narrative?: {
    text: string;
    model: string;
    stub: boolean;
    tokensIn: number;
    tokensOut: number;
    latencyMs: number;
  };
};

export type Adapter = {
  id: string;
  fqn: string;
  kind: string;
  pattern?: string;
};

export type CaptureDeployment = {
  id: string;
  environment: string;
  method: string;
  status: 'pending' | 'live' | 'paused' | 'stopped' | 'failed';
  sampleRate: number;
  startedAt?: string;
  stoppedAt?: string;
};

export type CaptureEnvelope = {
  id: string;
  operation: string;
  direction: 'REQUEST' | 'RESPONSE' | 'FAULT';
  partner: string;
  environment: string;
  size: number;
  capturedAt: string;
  sanitizationHits: number;
  correlationId: string;
};

export type SanitizationRuleStat = {
  id: string;
  name: string;
  strategy: 'hash' | 'redact' | 'tokenize' | 'leave' | string;
  hits: number;
  enabled: boolean;
  global: boolean;
  pattern?: string;
};

export type DeploymentDetail = {
  deployment: CaptureDeployment;
  totalEnvelopes: number;
  operationDistribution: Array<{ name: string; count: number }>;
  directionDistribution: Array<{ direction: string; count: number }>;
  recentEnvelopes: CaptureEnvelope[];
};

export type CaptureStatus = {
  deployments: CaptureDeployment[];
  totalEnvelopes: number;
  liveDeployments: number;
  operationDistribution: Array<{ name: string; count: number }>;
  recentEnvelopes: CaptureEnvelope[];
  sanitizationRules: SanitizationRuleStat[];
  startedAt?: string;
};

export type ElementView = {
  present: boolean;
  type?: string;
  format?: string;
  javaType?: string;
  adapter?: string;
  observed?: number;
  samples?: string[];
  enum?: string[];
  namespace?: string;
};

export type ReconElement = {
  id: string;
  path: string;
  vendorView: ElementView;
  codeView: ElementView;
  empiricView: ElementView;
};

export type ReconDecision = {
  id: string;
  path: string;
  kind: 'format_difference' | 'type_lenience' | 'enum_promotion' | 'missing_vendor' | 'rename' | string;
  impact: 'low' | 'medium' | 'high';
  agent: {
    action: string;
    rationale: string;
    alternatives: string[];
    model?: string;
    stub: boolean;
  };
  confidence: 'low' | 'medium' | 'high';
  resolution: 'pending' | 'accepted' | 'overridden' | 'escalated' | 'rejected';
  chosenAction?: string;
  note?: string;
  resolvedBy?: string;
  resolvedAt?: string;
};

export type ReconStatus = {
  run?: { id: string; status: string; startedAt: string; finishedAt?: string };
  decisions: ReconDecision[];
  elements: ReconElement[];
  counts: { total: number; pending: number; resolved: number };
};

export type GenFile = { path: string; sizeBytes: number };
export type GenRun = {
  id: string;
  startedAt: string;
  finishedAt?: string;
  status: 'running' | 'completed' | 'failed';
  aWsdlUri?: string;
  bindingsUri?: string;
  outputUri?: string;
  fileCount?: number;
  errorCount?: number;
  warningCount?: number;
  logText?: string;
};
export type GenStatus = {
  run?: GenRun;
  files: GenFile[];
};

export type DiffRun = {
  id: string;
  startedAt: string;
  finishedAt?: string;
  status: 'running' | 'completed' | 'failed';
  envelopesReplayed: number;
  passCount: number;
  benignCount: number;
  amberCount: number;
  redCount: number;
  isPromoted: boolean;
};

export type DiffOpStat = {
  name: string;
  total: number;
  pass: number;
  benign: number;
  amber: number;
  red: number;
};

export type Divergence = {
  id: string;
  replayId: string;
  operation?: string;
  kind: 'namespace_prefix' | 'element_ordering' | 'date_format' | 'type_precision'
       | 'missing_element' | 'extra_element' | 'enum_miss' | 'value_diff' | 'fault_diff' | string;
  bucket: 'benign' | 'amber' | 'red';
  xpath?: string;
  legacyValue?: string;
  newValue?: string;
  humanSummary?: string;
  agent: {
    action?: string;
    rationale?: string;
    model?: string;
    stub: boolean;
  };
  autofixProposal?: string;
  resolved: boolean;
  resolvedBy?: string;
  resolvedAt?: string;
};

export type DiffStatus = {
  run?: DiffRun;
  byOperation: DiffOpStat[];
  buckets: { benign: number; amber: number; red: number };
  divergences: Divergence[];
};

export type Bundle = {
  id: string;
  builtAt: string;
  status: 'building' | 'completed' | 'failed';
  bundleUri?: string;
  closureUri?: string;
  sizeBytes?: number;
  fileCount?: number;
  closureStub?: boolean;
};

export type ReportsStatus = {
  bundle?: Bundle;
};

export type ProvEntry = {
  id: string;
  projectId: string;
  ts: string;
  actorKind: 'agent' | 'human' | 'system';
  actorId: string;
  action: string;
  prompt?: any;
  model?: string;
  output?: any;
  toolCalls?: any;
  tokensIn?: number;
  tokensOut?: number;
  costUsd?: number;
  latencyMs?: number;
  links?: string[];
  humanReview?: any;
  /** OTel trace id (W3C traceparent format), populated since Phase 2C.3. */
  traceId?: string;
};

export type ProvAggregate = {
  total: number;
  byActor: Array<{ kind: string; count: number }>;
  byAction: Array<{ action: string; count: number }>;
  tokens: { in: number; out: number; cost: number };
};

export type UpliftModule = {
  id: string;
  name: string;
  packageName: string;
  fileCount: number;
  loc: number;
  difficulty: number;
  findingCount: number;
};

export type UpliftFinding = {
  id: string;
  moduleId: string;
  ruleId: string;
  ruleLabel: string;
  severity: 'low' | 'medium' | 'high';
  filePath: string;
  lineStart?: number;
  lineEnd?: number;
  snippet?: string;
  suggestedRecipe?: string;
};

export type UpliftStatus = {
  run?: { id: string; startedAt: string; finishedAt?: string; status: string; sourcePath: string };
  modules: UpliftModule[];
  findings: UpliftFinding[];
  ruleCounts: Array<{ ruleId: string; count: number }>;
};

export type RecipeModuleSummary = {
  id: string;
  name: string;
  packageName: string;
};

export type Recipe = {
  id: string;
  recipeId: string;
  label: string;
  description?: string;
  kind: 'ootb' | 'custom';
  status: 'proposed' | 'accepted' | 'rejected';
  notes?: string;
  findingCount: number;
  modules: RecipeModuleSummary[];
  decidedBy?: string;
  decidedAt?: string;
  createdAt: string;
};

export type RecipeStatus = {
  recipes: Recipe[];
  counts: { total: number; accepted: number; proposed: number; rejected: number };
  readyForGate: boolean;
};

export type RecipeFinding = {
  id: string;
  ruleId: string;
  ruleLabel: string;
  severity: 'low' | 'medium' | 'high';
  filePath: string;
  lineStart?: number;
  lineEnd?: number;
  snippet?: string;
};

export type StranglerRecipeRef = {
  id: string;
  recipeId: string;
  label: string;
  kind: 'ootb' | 'custom';
};

export type StranglerStep = {
  id: string;
  sequenceNo: number;
  moduleId?: string;
  module?: {
    id: string;
    name: string;
    packageName: string;
    fileCount: number;
    loc: number;
    difficulty: number;
    findingCount: number;
  };
  status: 'planned' | 'ready' | 'extracted';
  facadeNotes?: string;
  recipes: StranglerRecipeRef[];
  decidedBy?: string;
  decidedAt?: string;
  createdAt: string;
};

export type StranglerStatus = {
  steps: StranglerStep[];
  counts: { total: number; planned: number; ready: number; extracted: number };
  readyForGate: boolean;
};

export type MigrationRun = {
  id: string;
  stepId: string;
  moduleId?: string;
  startedAt: string;
  finishedAt?: string;
  status: 'running' | 'completed' | 'failed';
  summary: string;       // JSON encoded
  outputUri?: string;
  errorText?: string;
};

export type MigrationChange = {
  id: string;
  filePath: string;
  recipeId: string;
  changes: number;
};

export type MigrationStepResult = {
  run: MigrationRun | null;
  changes: MigrationChange[];
};

export type MigrationStatus = {
  runs: MigrationRun[];
  counts: { total: number; completed: number; failed: number; running: number };
  readyForGate: boolean;
};

export type MigrationDiff = {
  filePath: string;
  recipeId: string;
  changes: number;
  diff: string;
};

export type CharRun = {
  id: string;
  startedAt: string;
  finishedAt?: string;
  status: 'running' | 'completed' | 'failed';
  sampleSize: number;
  passCount: number;
  benignCount: number;
  regressionCount: number;
  errorText?: string;
};

export type CharCase = {
  id: string;
  moduleId?: string;
  testName: string;
  testKind: 'controller' | 'persistence' | 'jndi' | 'service' | 'domain' | string;
  inputSummary?: string;
  legacyOutput?: string;
  newOutput?: string;
  bucket: 'pass' | 'benign' | 'regression';
  diffKind?: string;
  aiRecommendation?: string;
  triageState: 'open' | 'accepted' | 'rejected' | 'fixed';
  triagedBy?: string;
  triagedAt?: string;
};

export type CharModuleSummary = {
  moduleId?: string;
  moduleName: string;
  packageName: string;
  pass: number;
  benign: number;
  regression: number;
};

export type CharStatus = {
  run: CharRun | null;
  cases: CharCase[];
  byModule: CharModuleSummary[];
  openRegressions: number;
  readyForGate: boolean;
};

export type CutoverChecklistItem = {
  id: string;
  text: string;
  category: string;
  done: boolean;
};

export type Cutover = {
  id: string;
  stepId?: string;
  moduleId?: string;
  module?: {
    id: string;
    name: string;
    packageName: string;
    loc: number;
    difficulty: number;
  };
  state: 'planned' | 'shadow' | 'canary' | 'live' | 'rolled_back' | 'decommissioned';
  trafficPercent: number;
  cutoverDate?: string;
  rollbackPlan?: string;
  notes?: string;
  checklist: CutoverChecklistItem[];
  approvedBy?: string;
  approvedAt?: string;
};

export type CutoverStatus = {
  cutovers: Cutover[];
  counts: {
    total: number;
    planned: number;
    shadow: number;
    canary: number;
    live: number;
    rolledBack: number;
    decommissioned: number;
  };
  readyForGate: boolean;
};

export type Workspace = {
  id: string;
  name: string;
  ownerEmail: string;
};

/**
 * Source-ingestion status returned by every
 * /api/v1/projects/{id}/sources/* endpoint. The state machine is:
 *   pending → cloning|extracting → ready  |  error
 * Once {@code ready}, {@code sourcePath} is the absolute path inside
 * the analysis-services container (mounted at {@code /uploads}); the
 * SPA never has to read it — it just hands the project off to Stage A.
 */
export type IngestStatus = {
  projectId:   string;
  state:       'pending' | 'cloning' | 'extracting' | 'ready' | 'error';
  mode:        'github' | 'upload' | null;
  message:     string;
  sourcePath:  string | null;
  bytes:       number;
  files:       number;
  startedAt:   string | null;
  finishedAt:  string | null;
};

// ---------------------------------------------------------------------------
// Phase 2L cost-attribution rollup. Mirrors prov-service's response shape;
// every cell is server-computed so the UI just renders. costUsd is sometimes
// a string (Jackson serialises BigDecimal as JSON string) and sometimes a
// number — coerce on read with Number(...) at the call site rather than
// trying to be precise in TS.
// ---------------------------------------------------------------------------
export type WorkspaceCost = {
  workspaceId: string;
  rangeStart: string;          // ISO-8601
  rangeEnd: string;            // ISO-8601
  totals: {
    calls: number;
    tokensIn: number;
    tokensOut: number;
    costUsd: number | string;
  };
  byUser:    Array<{ userEmail: string; calls: number; costUsd: number | string }>;
  byProject: Array<{ projectId: string; calls: number; costUsd: number | string }>;
  byModel:   Array<{ model:    string; calls: number; costUsd: number | string }>;
  daily:     Array<{ day:      string; calls: number; costUsd: number | string }>;
};

// Generated from `openapi/gateway.json`. Re-exported as the
// public type so existing call-sites keep importing `Identity` from
// here without knowing about the codegen layer. To regenerate:
//   cd frontend && npm run codegen
import type { components as GatewayComponents } from './generated/gateway';
export type Identity = GatewayComponents['schemas']['Identity'];

const DEFAULT_WS = '00000000-0000-0000-0000-000000000001';

/** HTTP methods the gateway treats as mutating. Mirror of
 *  IdempotencyFilter.isMutating server-side. */
const MUTATING_METHODS = new Set(['POST', 'PUT', 'PATCH', 'DELETE']);

/**
 * Generates an Idempotency-Key. Uses crypto.randomUUID where supported
 * (modern browsers + jsdom 22+); falls back to a hand-built v4 hex
 * string for the (rare) older environment. The shape conforms to RFC
 * 4122 v4 either way; the server doesn't actually validate the format.
 */
function newIdempotencyKey(): string {
  if (typeof crypto !== 'undefined' && typeof crypto.randomUUID === 'function') {
    return crypto.randomUUID();
  }
  const buf = new Uint8Array(16);
  if (typeof crypto !== 'undefined' && crypto.getRandomValues) {
    crypto.getRandomValues(buf);
  } else {
    for (let i = 0; i < buf.length; i++) buf[i] = Math.floor(Math.random() * 256);
  }
  buf[6] = (buf[6] & 0x0f) | 0x40;  // version 4
  buf[8] = (buf[8] & 0x3f) | 0x80;  // variant 10
  const hex = Array.from(buf, b => b.toString(16).padStart(2, '0')).join('');
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`;
}

/**
 * Build the headers for every API call:
 *  - Content-Type: application/json
 *  - Authorization: Bearer <token>, when a non-expired token is in storage
 *  - Idempotency-Key on POST/PUT/PATCH/DELETE so retries from a flaky
 *    network don't double-write. The server caches the response under
 *    `(method, path, key)` for 10 min — see IdempotencyFilter.
 *  - …plus any caller-supplied overrides (last writer wins)
 */
function authHeaders(method: string, extra?: HeadersInit): HeadersInit {
  const out: Record<string, string> = { 'Content-Type': 'application/json' };
  const token = getToken();
  if (token) out['Authorization'] = `Bearer ${token}`;
  if (MUTATING_METHODS.has(method.toUpperCase())) {
    out['Idempotency-Key'] = newIdempotencyKey();
  }
  return { ...out, ...(extra as Record<string, string>) };
}

/**
 * Thrown when the gateway responds 403. Carries enough context for the
 * UI to show a helpful "this action requires <role>" message instead of
 * a generic "request failed" toast.
 */
export class ForbiddenError extends Error {
  constructor(message: string, readonly path: string) {
    super(message);
    this.name = 'ForbiddenError';
  }
}

async function http<T>(path: string, init?: RequestInit): Promise<T> {
  const method = (init?.method ?? 'GET').toUpperCase();
  const res = await fetch(`${API_BASE}${path}`, {
    ...init,
    headers: authHeaders(method, init?.headers)
  });
  // 401 means the token is gone, expired, or never existed. Wipe whatever
  // we have so the AuthGate boundary in App.tsx flips to the login redirect.
  if (res.status === 401) {
    clearToken();
    throw new Error('401 Unauthorized');
  }
  // 403 means the user is signed in but lacks the role for this path.
  // Don't clear the token — the UI just needs to surface a clearer
  // message. Finalize buttons in particular check for this.
  if (res.status === 403) {
    throw new ForbiddenError(
        'This action requires a higher role (typically Tech Lead).',
        path);
  }
  if (!res.ok) throw new Error(`${res.status} ${res.statusText}`);
  return res.json() as Promise<T>;
}

export const api = {
  me: () => http<Identity>('/api/v1/me'),
  workspaces: () => http<Workspace[]>('/api/v1/workspaces'),
  projects: (wsId: string = DEFAULT_WS) =>
    http<Project[]>(`/api/v1/workspaces/${wsId}/projects`),
  project: (id: string) => http<Project>(`/api/v1/projects/${id}`),
  createProject: (body: Partial<Project> & { name: string; mode: string }) =>
    http<Project>('/api/v1/projects', {
      method: 'POST',
      body: JSON.stringify({ workspaceId: DEFAULT_WS, ...body })
    }),
  attachSource: (id: string, path: string) =>
    http<Project>(`/api/v1/projects/${id}/sources`, {
      method: 'POST',
      body: JSON.stringify({ path })
    }),
  runArchaeology: (id: string) =>
    http<{ runId: string; status: string }>(`/api/v1/projects/${id}/stages/archaeology/run`, {
      method: 'POST'
    }),
  operations: (id: string) =>
    http<Operation[]>(`/api/v1/projects/${id}/operations`),
  adapters: (id: string) =>
    http<Adapter[]>(`/api/v1/projects/${id}/adapters`),

  startCapture: (id: string, targetEnvelopes = 250) =>
    http<{ ok: boolean; totalEnvelopes: number; faults: number }>(
      `/api/v1/projects/${id}/stages/capture/deploy`,
      { method: 'POST', body: JSON.stringify({ targetEnvelopes }) }
    ),
  finalizeCapture: (id: string) =>
    http<{ ok: boolean }>(
      `/api/v1/projects/${id}/stages/capture/finalize`,
      { method: 'POST' }
    ),
  captureStatus: (id: string) =>
    http<CaptureStatus>(`/api/v1/projects/${id}/stages/capture/status`),
  deploymentDetail: (projectId: string, deploymentId: string) =>
    http<DeploymentDetail>(
      `/api/v1/projects/${projectId}/stages/capture/deployments/${deploymentId}`),
  updateDeployment: (projectId: string, deploymentId: string, body: { sampleRate?: number }) =>
    http<{ ok: boolean; deployment: CaptureDeployment }>(
      `/api/v1/projects/${projectId}/stages/capture/deployments/${deploymentId}`,
      { method: 'PUT', body: JSON.stringify(body) }
    ),
  updateSanitizationRule: (projectId: string, ruleId: string,
                           body: { enabled?: boolean; strategy?: string }) =>
    http<{ ok: boolean }>(
      `/api/v1/projects/${projectId}/stages/capture/sanitization-rules/${ruleId}`,
      { method: 'PUT', body: JSON.stringify(body) }
    ),

  runReconciliation: (id: string) =>
    http<{ runId: string; status: string }>(
      `/api/v1/projects/${id}/stages/reconciliation/run`,
      { method: 'POST' }
    ),
  reconStatus: (id: string) =>
    http<ReconStatus>(`/api/v1/projects/${id}/stages/reconciliation/status`),
  resolveDecision: (
    projectId: string,
    decisionId: string,
    body: { choice: 'accepted' | 'overridden' | 'escalated' | 'rejected'; action?: string; note?: string; user?: string }
  ) =>
    http<{ ok: boolean }>(
      `/api/v1/projects/${projectId}/decisions/${decisionId}/resolve`,
      { method: 'POST', body: JSON.stringify(body) }
    ),

  runGeneration: (id: string, basePackage = 'com.envestnet.broadridge') =>
    http<{ runId: string; status: string; fileCount: number; errorCount: number; warningCount: number }>(
      `/api/v1/projects/${id}/stages/generation/run`,
      { method: 'POST', body: JSON.stringify({ basePackage }) }
    ),
  generationStatus: (id: string) =>
    http<GenStatus>(`/api/v1/projects/${id}/stages/generation/status`),

  // The bindings .xjb is XML, not JSON — use a dedicated text fetcher.
  generationBindings: async (id: string) => {
    const res = await fetch(`${API_BASE}/api/v1/projects/${id}/stages/generation/bindings`,
                            { headers: authHeaders('GET') });
    if (res.status === 401) { clearToken(); throw new Error('401 Unauthorized'); }
    if (!res.ok) throw new Error(`${res.status} ${res.statusText}`);
    return res.text();
  },
  authoritativeWsdlUrl: (id: string) =>
    `${API_BASE}/api/v1/projects/${id}/wsdl/authoritative`,
  generationDownloadUrl: (id: string) =>
    `${API_BASE}/api/v1/projects/${id}/stages/generation/output.zip`,

  runDiff: (id: string, sampleSize = 250) =>
    http<{ runId: string; status: string; envelopesReplayed: number;
           passCount: number; benignCount: number; amberCount: number; redCount: number }>(
      `/api/v1/projects/${id}/stages/diff/run`,
      { method: 'POST', body: JSON.stringify({ sampleSize }) }
    ),
  diffStatus: (id: string) =>
    http<DiffStatus>(`/api/v1/projects/${id}/stages/diff/status`),
  autoFixDivergence: (projectId: string, divId: string, user?: string) =>
    http<{ ok: boolean; patch: string }>(
      `/api/v1/projects/${projectId}/divergences/${divId}/auto-fix`,
      // Default to the signed-in identity rather than a hardcoded
      // dev string. `user` stays optional so callers can override.
      { method: 'POST', body: JSON.stringify({ user: user ?? currentIdentity()?.email }) }
    ),

  buildBundle: (id: string) =>
    http<{ bundleId: string; status: string; fileCount: number; sizeBytes: number; closureStub: boolean }>(
      `/api/v1/projects/${id}/stages/reports/build`,
      { method: 'POST' }
    ),
  reportsStatus: (id: string) =>
    http<ReportsStatus>(`/api/v1/projects/${id}/stages/reports/status`),
  closureMarkdown: async (id: string) => {
    const res = await fetch(`${API_BASE}/api/v1/projects/${id}/stages/reports/closure`,
                            { headers: authHeaders('GET') });
    if (res.status === 401) { clearToken(); throw new Error('401 Unauthorized'); }
    if (!res.ok) throw new Error(`${res.status} ${res.statusText}`);
    return res.text();
  },
  bundleDownloadUrl: (id: string) =>
    `${API_BASE}/api/v1/projects/${id}/stages/reports/bundle.zip`,

  provenance: (id: string, opts?: {
    action?: string; actorKind?: string; actorId?: string; q?: string; limit?: number
  }) => {
    const p = new URLSearchParams();
    if (opts?.action)    p.set('action',    opts.action);
    if (opts?.actorKind) p.set('actorKind', opts.actorKind);
    if (opts?.actorId)   p.set('actorId',   opts.actorId);
    if (opts?.q)         p.set('q',         opts.q);
    if (opts?.limit)     p.set('limit',     String(opts.limit));
    const qs = p.toString();
    return http<ProvEntry[]>(
      `/api/v1/projects/${id}/provenance${qs ? '?' + qs : ''}`);
  },
  provenanceAggregate: (id: string) =>
    http<ProvAggregate>(`/api/v1/projects/${id}/provenance/aggregate`),
  provenanceExportUrl: (id: string) =>
    `${API_BASE}/api/v1/projects/${id}/provenance/export.csv`,

  runInventory: (id: string) =>
    http<{ runId: string; status: string }>(
      `/api/v1/projects/${id}/stages/inventory/run`,
      { method: 'POST' }
    ),
  inventoryStatus: (id: string) =>
    http<UpliftStatus>(`/api/v1/projects/${id}/stages/inventory/status`),

  seedRecipes: (id: string) =>
    http<{ ok: boolean; count: number }>(
      `/api/v1/projects/${id}/stages/recipes/seed`,
      { method: 'POST', body: '{}' }
    ),
  recipesStatus: (id: string) =>
    http<RecipeStatus>(`/api/v1/projects/${id}/stages/recipes/status`),
  decideRecipe: (id: string, recipeId: string,
                 body: { status: 'proposed' | 'accepted' | 'rejected'; notes?: string; user?: string }) =>
    http<{ ok: boolean; id: string; status: string }>(
      `/api/v1/projects/${id}/stages/recipes/${recipeId}/decision`,
      { method: 'POST', body: JSON.stringify(body) }
    ),
  createCustomRecipe: (id: string,
                       body: { recipeId: string; label: string; description?: string; notes?: string; user?: string }) =>
    http<{ ok: boolean; id: string }>(
      `/api/v1/projects/${id}/stages/recipes`,
      { method: 'POST', body: JSON.stringify(body) }
    ),
  deleteRecipe: (id: string, recipeId: string) =>
    http<{ ok: boolean }>(
      `/api/v1/projects/${id}/stages/recipes/${recipeId}`,
      { method: 'DELETE' }
    ),
  recipeFindings: (id: string, recipeId: string) =>
    http<{ findings: RecipeFinding[] }>(
      `/api/v1/projects/${id}/stages/recipes/${recipeId}/findings`
    ),
  finalizeRecipes: (id: string) =>
    http<{ ok: boolean; currentStage: string } | { error: string }>(
      `/api/v1/projects/${id}/stages/recipes/finalize`,
      { method: 'POST', body: '{}' }
    ),

  seedStrangler: (id: string) =>
    http<{ ok: boolean; count: number }>(
      `/api/v1/projects/${id}/stages/strangler/seed`,
      { method: 'POST', body: '{}' }
    ),
  stranglerStatus: (id: string) =>
    http<StranglerStatus>(`/api/v1/projects/${id}/stages/strangler/status`),
  updateStranglerStep: (id: string, stepId: string,
                        body: { status?: 'planned' | 'ready' | 'extracted'; facadeNotes?: string; user?: string }) =>
    http<{ ok: boolean }>(
      `/api/v1/projects/${id}/stages/strangler/${stepId}`,
      { method: 'PUT', body: JSON.stringify(body) }
    ),
  reorderStranglerStep: (id: string, stepId: string, delta: number) =>
    http<{ ok: boolean }>(
      `/api/v1/projects/${id}/stages/strangler/${stepId}/order`,
      { method: 'PUT', body: JSON.stringify({ delta }) }
    ),
  deleteStranglerStep: (id: string, stepId: string) =>
    http<{ ok: boolean }>(
      `/api/v1/projects/${id}/stages/strangler/${stepId}`,
      { method: 'DELETE' }
    ),
  finalizeStrangler: (id: string) =>
    http<{ ok: boolean; currentStage: string } | { error: string }>(
      `/api/v1/projects/${id}/stages/strangler/finalize`,
      { method: 'POST', body: '{}' }
    ),

  runMigration: (id: string, stepId: string) =>
    http<{ ok: boolean; runId: string; status: string }>(
      `/api/v1/projects/${id}/stages/migration/${stepId}/run`,
      { method: 'POST', body: '{}' }
    ),
  migrationForStep: (id: string, stepId: string) =>
    http<MigrationStepResult>(
      `/api/v1/projects/${id}/stages/migration/step/${stepId}`
    ),
  migrationStatus: (id: string) =>
    http<MigrationStatus>(`/api/v1/projects/${id}/stages/migration/status`),
  migrationDiff: (id: string, runId: string, path: string) =>
    http<MigrationDiff>(
      `/api/v1/projects/${id}/stages/migration/diff?runId=${runId}&path=${encodeURIComponent(path)}`
    ),
  finalizeMigration: (id: string) =>
    http<{ ok: boolean; currentStage: string } | { error: string }>(
      `/api/v1/projects/${id}/stages/migration/finalize`,
      { method: 'POST', body: '{}' }
    ),

  runCharacterization: (id: string, casesPerModule = 30) =>
    http<{ ok: boolean; runId: string; passCount: number; benignCount: number; regressionCount: number }>(
      `/api/v1/projects/${id}/stages/characterize/run`,
      { method: 'POST', body: JSON.stringify({ casesPerModule }) }
    ),
  characterizeStatus: (id: string) =>
    http<CharStatus>(`/api/v1/projects/${id}/stages/characterize/status`),
  triageCharCase: (id: string, caseId: string,
                   body: { state: 'open' | 'accepted' | 'rejected' | 'fixed'; user?: string }) =>
    http<{ ok: boolean; state: string }>(
      `/api/v1/projects/${id}/stages/characterize/cases/${caseId}/triage`,
      { method: 'POST', body: JSON.stringify(body) }
    ),
  finalizeCharacterization: (id: string) =>
    http<{ ok: boolean; currentStage: string } | { error: string }>(
      `/api/v1/projects/${id}/stages/characterize/finalize`,
      { method: 'POST', body: '{}' }
    ),

  seedCutover: (id: string) =>
    http<{ ok: boolean; count: number }>(
      `/api/v1/projects/${id}/stages/cutover/seed`,
      { method: 'POST', body: '{}' }
    ),
  cutoverStatus: (id: string) =>
    http<CutoverStatus>(`/api/v1/projects/${id}/stages/cutover/status`),
  updateCutover: (id: string, cutoverId: string,
                  body: { state?: Cutover['state']; trafficPercent?: number; notes?: string; user?: string }) =>
    http<{ ok: boolean; state: Cutover['state']; trafficPercent: number }>(
      `/api/v1/projects/${id}/stages/cutover/${cutoverId}`,
      { method: 'PUT', body: JSON.stringify(body) }
    ),
  toggleCutoverChecklist: (id: string, cutoverId: string, itemId: string, done: boolean) =>
    http<{ ok: boolean }>(
      `/api/v1/projects/${id}/stages/cutover/${cutoverId}/checklist/${itemId}`,
      { method: 'PUT', body: JSON.stringify({ done }) }
    ),
  cutoverClosureMarkdown: async (id: string) => {
    const res = await fetch(`${API_BASE}/api/v1/projects/${id}/stages/cutover/closure`,
                            { headers: authHeaders('GET') });
    if (res.status === 401) { clearToken(); throw new Error('401 Unauthorized'); }
    if (!res.ok) throw new Error(`${res.status} ${res.statusText}`);
    return res.text();
  },
  cutoverClosureUrl: (id: string) =>
    `${API_BASE}/api/v1/projects/${id}/stages/cutover/closure`,
  finalizeCutover: (id: string) =>
    http<{ ok: boolean; complete: boolean; currentStage: string } | { error: string }>(
      `/api/v1/projects/${id}/stages/cutover/finalize`,
      { method: 'POST', body: '{}' }
    ),

  // ---------------------------------------------------------------
  // Source ingestion — ingestion options surfaced in NewProjectForm.
  // Backend lives at prj-service /api/v1/projects/{id}/sources/*.
  // Both `ingestGithub` and `ingestUpload` are synchronous from the
  // SPA's perspective (the server holds the connection until the
  // clone / extraction completes — ~5–15s typical), so the caller
  // can show a single spinner instead of polling.
  // ---------------------------------------------------------------
  ingestGithub: (projectId: string, body: { url: string; branch?: string; subpath?: string }) =>
    http<IngestStatus>(
      `/api/v1/projects/${projectId}/sources/github`,
      { method: 'POST', body: JSON.stringify(body) }
    ),
  ingestUpload: async (projectId: string, file: File): Promise<IngestStatus> => {
    // Multipart can't use the shared http() helper (which is
    // JSON-only); hand-roll the request but reuse the auth-header
    // logic + 401 handling for consistency.
    const fd = new FormData();
    fd.append('file', file);
    const res = await fetch(`${API_BASE}/api/v1/projects/${projectId}/sources/upload`, {
      method: 'POST',
      headers: authHeaders('POST'),
      body: fd
    });
    if (res.status === 401) { clearToken(); throw new Error('401 Unauthorized'); }
    if (!res.ok) throw new Error(`${res.status} ${res.statusText}`);
    return res.json() as Promise<IngestStatus>;
  },
  ingestStatus: (projectId: string) =>
    http<IngestStatus>(`/api/v1/projects/${projectId}/sources/status`),

  // ---------------------------------------------------------------
  // Stage F · Build & Test gate. SOAP: javac/mvn compile against the
  // wsimport-generated tree. UPLIFT: mvn test against the OpenRewrite-
  // modified source. Surfaces pass/fail counts + failure names.
  // ---------------------------------------------------------------
  runBuildTest: (projectId: string) =>
    http<BuildTestResult>(
      `/api/v1/projects/${projectId}/stages/build/run`,
      { method: 'POST' }
    ),
  buildTestStatus: (projectId: string) =>
    http<{ run: BuildTestRun | null }>(
      `/api/v1/projects/${projectId}/stages/build/status`
    ),

  // ---------------------------------------------------------------
  // Workspace insights - the "Atlas at work" KPI strip on the
  // dashboard. One round trip returns project count, vendor count,
  // pattern count, decisions remembered, and an hours-saved estimate.
  // ---------------------------------------------------------------
  workspaceInsights: (wsId: string = DEFAULT_WS) =>
    http<WorkspaceInsights>(`/api/v1/workspaces/${wsId}/insights`),

  // ---------------------------------------------------------------
  // Reconciliation Pattern Library — cross-project recommendations
  // surfaced on Stage C decision cards. Vendor-scoped; rows arrive
  // sorted by occurrence_count desc.
  // ---------------------------------------------------------------
  reconPatterns: (projectId: string) =>
    http<ReconPatternsResponse>(
      `/api/v1/projects/${projectId}/recon/patterns`
    ),

  // ---------------------------------------------------------------
  // Migration Forecast — the pre-Stage-A effort estimate. Calls
  // arch-service for a structural peek of the cloned source, then
  // grounds an LLM forecast on the result. Synchronous; typical
  // runtime ~10-15s on a small SOAP project.
  // ---------------------------------------------------------------
  runForecast: (projectId: string) =>
    http<MigrationForecast>(
      `/api/v1/projects/${projectId}/forecast/run`,
      { method: 'POST' }
    ),
  getForecast: async (projectId: string): Promise<MigrationForecast | null> => {
    const res = await fetch(`${API_BASE}/api/v1/projects/${projectId}/forecast`, {
      headers: { Authorization: `Bearer ${getToken() ?? ''}` }
    });
    if (res.status === 404) return null;
    if (res.status === 401) { clearToken(); throw new Error('401 Unauthorized'); }
    if (!res.ok) throw new Error(`${res.status} ${res.statusText}`);
    return res.json() as Promise<MigrationForecast>;
  },

  // Phase 2L — per-workspace LLM cost rollup. `from`/`to` are
  // optional ISO-8601 instants; server default is the trailing 30
  // days when omitted.
  workspaceCost: (wsId: string = DEFAULT_WS, opts?: { from?: string; to?: string }) => {
    const q = new URLSearchParams();
    if (opts?.from) q.set('from', opts.from);
    if (opts?.to)   q.set('to',   opts.to);
    const qs = q.toString();
    return http<WorkspaceCost>(
      `/api/v1/workspaces/${wsId}/cost${qs ? `?${qs}` : ''}`
    );
  },

  defaultWorkspaceId: DEFAULT_WS
};
